   <?php
    try {
        // Base Ingredients
        $baseItems = $conn->query("
        SELECT ii.item_id, ii.item_name, ii.quantity, ii.unit, ii.status, ii.date_made, ii.date_expiry, s.staff_name AS added_by
        FROM inventory_item ii
        JOIN staff_info s ON ii.added_by = s.staff_id
        WHERE ii.inv_category_id = 3
        ORDER BY ii.item_name
    ")->fetchAll(PDO::FETCH_ASSOC);

        // Ingredients grouped by category
        $rows = $conn->query("
        SELECT ii.*, s.staff_name, c.category_name
        FROM inventory_item ii
        JOIN staff_info s ON ii.added_by = s.staff_id
        LEFT JOIN category c ON ii.category_id = c.category_id
        WHERE ii.inv_category_id = 1
        ORDER BY c.category_name, ii.item_name
    ")->fetchAll(PDO::FETCH_ASSOC);

        $ingredientsByCat = [];
        foreach ($rows as $row) {
            $cat = $row['category_name'] ?? 'Uncategorized';
            $ingredientsByCat[$cat][] = $row;
        }

        // Materials
        $materials = $conn->query("
        SELECT ii.*, s.staff_name
        FROM inventory_item ii
        JOIN staff_info s ON ii.added_by = s.staff_id
        WHERE ii.inv_category_id = 2
        ORDER BY ii.item_name
    ")->fetchAll(PDO::FETCH_ASSOC);
    } catch (PDOException $e) {
        $baseItems = $materials = $ingredientsByCat = [];
    }

    ?>

   <!-- Inventory Form -->
   <form id="inventoryUploadForm" enctype="multipart/form-data" class="space-y-8 bg-[var(--background-color)] text-[var(--text-color)] border border-[var(--border-color)] p-8 rounded-xl shadow-lg max-w-2xl mx-auto">

       <!-- Form Title -->
       <h2 class="text-2xl font-bold  mb-4 text-center">Inventory Management</h2>

       <!-- Upload Inventory File -->
       <div class="flex flex-col">
           <label for="inventoryFile" class="mb-2 font-medium ">Upload Inventory File (Excel/CSV)</label>
           <input type="file" id="inventoryFile" name="inventory_file" accept=".xlsx,.xls,.csv"
               class="w-full rounded-md p-3  border border-[var(--border-color)] hover:border-blue-400 focus:outline-none focus:ring-2 focus:ring-blue-300 transition">
           <!-- 📘 Important Note -->
           <p class="mt-2 text-sm text-red-600 bg-red-50 border border-red-200 rounded-md p-2">
               <strong>Note:</strong> Only Excel files generated by this system are accepted.
               Please download the template first and update your inventory using that format.
           </p>
       </div>

       <!-- Generate Template Button -->
       <div class="flex justify-start">
           <button type="button" id="generateTemplate"
               class="flex items-center gap-2 bg-blue-500 text-white px-6 py-2 rounded-md hover:bg-blue-600 transition shadow-sm">
               <i class="fa-solid fa-file-arrow-down"></i> Download Template
           </button>
       </div>

       <!-- Submit Button -->
       <div class="flex justify-end">
           <button type="button" id="submitInventory"
               class="bg-green-500 text-white font-semibold px-6 py-2 rounded-md hover:bg-green-600 transition shadow-sm">
               Submit Inventory
           </button>
       </div>

       <!-- Printable Report Modal -->
       <div id="printReportModal"
           class="hidden fixed inset-0 bg-black/50 flex items-center justify-center z-50 overflow-auto p-4">
           <div class="bg-white p-6 rounded-xl w-full max-w-4xl shadow-lg relative">

               <!-- Close Button -->
               <button onclick="closeReport()"
                   class="absolute top-4 right-4 px-4 py-2 bg-red-500 text-white rounded hover:bg-red-600 transition shadow">
                   Close
               </button>

               <!-- Print Button -->
               <button onclick="printReport()"
                   class="absolute top-4 right-24 px-4 py-2 bg-green-500 text-white rounded hover:bg-green-600 transition shadow">
                   Print
               </button>

               <div id="reportContent" class="mt-12 overflow-auto max-h-[70vh]"></div>
           </div>
       </div>

   </form>


   <!-- SheetJS -->
   <script src="https://cdn.sheetjs.com/xlsx-latest/package/dist/xlsx.full.min.js"></script>
   <script>
       const baseItems = <?php echo json_encode($baseItems); ?>;
       const ingredientsByCat = <?php echo json_encode($ingredientsByCat); ?>;
       const materials = <?php echo json_encode($materials); ?>;

       // ✅ Validate uploaded Excel
       document.getElementById('inventoryFile').addEventListener('change', function() {
           const file = this.files[0];
           if (!file) return;

           const validExt = /\.xlsx$/i;
           if (!validExt.test(file.name)) {
               Swal.fire({
                   icon: 'error',
                   title: 'Invalid File Type',
                   text: 'Only .xlsx Excel files generated by this system are accepted.',
                   confirmButtonColor: '#3085d6'
               });
               this.value = '';
               return;
           }

           const reader = new FileReader();
           reader.onload = function(e) {
               const data = new Uint8Array(e.target.result);
               const workbook = XLSX.read(data, {
                   type: 'array'
               });

               const expectedSheets = ['Base Ingredients', 'Materials', ...Object.keys(ingredientsByCat)];
               const missingSheets = expectedSheets.filter(s => !workbook.SheetNames.includes(s));

               if (missingSheets.length > 0) {
                   Swal.fire({
                       icon: 'error',
                       title: 'Invalid Excel Template',
                       text: `Missing sheet(s): ${missingSheets.join(', ')}`,
                   });
                   document.getElementById('inventoryFile').value = '';
                   return;
               }

               const firstSheet = workbook.Sheets[expectedSheets[0]];
               const headers = XLSX.utils.sheet_to_json(firstSheet, {
                   header: 1
               })[0] || [];
               const validHeaders = ['Item Name', 'Unit', 'Quantity'];
               const hasValidHeaders = validHeaders.every((h, i) => headers[i] === h);

               if (!hasValidHeaders) {
                   Swal.fire({
                       icon: 'error',
                       title: 'Invalid Data Format',
                       text: 'Column headers must be: Item Name, Unit, Quantity',
                   });
                   document.getElementById('inventoryFile').value = '';
                   return;
               }

               Swal.fire({
                   icon: 'success',
                   title: 'File Accepted',
                   text: `File "${file.name}" is valid and ready for upload.`,
                   timer: 2000,
                   showConfirmButton: false
               });
           };
           reader.readAsArrayBuffer(file);
       });

       // 🧾 Generate Excel Template
       document.getElementById('generateTemplate').addEventListener('click', () => {
           const wb = XLSX.utils.book_new();

           function createSheet(items, sheetName) {
               const sheetData = [
                   ['Item Name', 'Unit', 'Quantity']
               ];
               items.forEach(item => sheetData.push([item.item_name || '', item.unit || '', '']));
               XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(sheetData), sheetName.substring(0, 31));
           }

           createSheet(baseItems, 'Base Ingredients');
           Object.keys(ingredientsByCat).forEach(cat => createSheet(ingredientsByCat[cat], cat));
           createSheet(materials, 'Materials');
           XLSX.writeFile(wb, 'Inventory_Template.xlsx');
       });

       // 📤 Submit Inventory (does not block other forms)
       document.getElementById('submitInventory').addEventListener('click', function() {
           const fileInput = document.getElementById('inventoryFile'); // ✅ Correct target

           if (!fileInput.files[0]) {
               Swal.fire({
                   icon: 'info',
                   title: 'No File Selected',
                   text: 'Please upload an inventory file before submitting.',
               });
               return;
           }

           const reader = new FileReader();
           reader.onload = function(e) {
               const data = new Uint8Array(e.target.result);
               const workbook = XLSX.read(data, {
                   type: 'array'
               });

               const categories = {
                   'Base Ingredients': baseItems,
                   'Materials': materials,
                   ...ingredientsByCat
               };

               const inventoryData = [];
               workbook.SheetNames.forEach(sheetName => {
                   if (!categories[sheetName]) return;
                   const items = categories[sheetName];
                   const rows = XLSX.utils.sheet_to_json(workbook.Sheets[sheetName], {
                       header: 1
                   }).slice(1);

                   items.forEach(item => {
                       const row = rows.find(r => r[0] === item.item_name);
                       const actual = row ? parseFloat(row[2]) || 0 : 0;
                       const variance = actual - (item.quantity || 0);

                       inventoryData.push({
                           sheet: sheetName,
                           item_name: item.item_name,
                           unit: item.unit,
                           system_count: item.quantity || 0,
                           actual_count: actual,
                           variance: variance
                       });
                   });
               });

               const formData = new FormData();
               formData.append('inventory_json', JSON.stringify(inventoryData));

               Swal.fire({
                   title: 'Processing Inventory...',
                   html: 'Please wait while we generate the report.',
                   allowOutsideClick: false,
                   didOpen: () => Swal.showLoading()
               });

               fetch('../../app/includes/managerModule/print_inventory.php', {
                       method: 'POST',
                       body: formData
                   })
                   .then(res => res.text())
                   .then(html => {
                       Swal.close();
                       Swal.fire({
                           icon: 'success',
                           title: 'Inventory Processed',
                           text: 'Inventory report has been generated successfully!',
                       }).then(() => {
                           const printWindow = window.open('', '_blank');
                           printWindow.document.open();
                           printWindow.document.write(html);
                           printWindow.document.close();
                       });
                   })
                   .catch(err => {
                       Swal.fire({
                           icon: 'error',
                           title: 'Error',
                           text: 'Error generating report: ' + err
                       });
                   });
           };

           reader.readAsArrayBuffer(fileInput.files[0]);
       });
   </script>